import AnimeList from '@wikinime/components/anime-list'
import Anime from '@wikinime/models/anime'
import Page from '@wikinime/models/paging'
import { getAnimes } from '@wikinime/services/anime-services'
import { GetStaticProps, InferGetStaticPropsType } from 'next'
import Head from 'next/head'

export default function HomePage({ initialAnimes }: InferGetStaticPropsType<typeof getStaticProps>) {
  return (
    <>
      <Head>
        <title>Wikinime | Find Your Favorites Anime Here</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <AnimeList initial={initialAnimes} />
    </>
  )
}

export const getStaticProps: GetStaticProps<{ initialAnimes: Page<Anime> }> = async () => {
  const initialAnimes = await getAnimes({ page: 1, perPage: 20 })
  return { props: { initialAnimes }, revalidate: 60 }
}
