import AnimeList from '@wikinime/components/anime-list'
import Head from 'next/head'

export default function HomePage() {
  return (
    <>
      <Head>
        <title>Wikinime | Find Your Favorites Anime Here</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <AnimeList />
    </>
  )
}
